channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - geopandas
  - contextily
  - rasterio
  - cartopy
  - geoplot
  - mapclassify
  - folium
  - ipyleaflet
  - rasterstats
  - jupyter
  - jupyterlab
  - adjustText
  - tk
  - tcl
  - matplotlib-scalebar
  
